name: Docker

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

      tag:
        required: true
        type: string

      context:
        required: false
        type: string
        default: "."

      platforms:
        required: false
        type: string
        default: "linux/amd64,linux/arm64"

      push:
        required: false
        type: boolean
        default: true

      dockerfile:
        required: false
        type: string

jobs:
  docker-workflow:
    name: "${{ inputs.image }}:${{ inputs.tag }}"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          push: ${{ inputs.push }}
          file: ${{ inputs.dockerfile || format('{0}/Dockerfile', inputs.context) }}
          tags: ${{ inputs.image }}:${{ inputs.tag }}
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
